name: Build Win7 Clash

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-win7:
    name: Build Win7 Clash
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: win7-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            win7-cargo

      - name: Install Rust 1.77.2
        run: rustup install 1.77.2

      - name: Override to use Rust 1.77.2
        run: rustup default 1.77.2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"

      - name: Build Win7 binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Rename binary
        run: |
          mkdir -p build
          mv target/x86_64-win7-windows-msvc/debug/clash-rs.exe build/clash-win7.exe

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: clash-win7
          path: build/clash-win7.exe
